/* 
 * DDStore API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DdFileApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DdFileApiTests
    {
        private DdFileApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DdFileApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DdFileApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DdFileApi
            //Assert.IsInstanceOfType(typeof(DdFileApi), instance, "instance is a DdFileApi");
        }

        
        /// <summary>
        /// Test GetDdfileByRef
        /// </summary>
        [Test]
        public void GetDdfileByRefTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xmlref = null;
            //string format = null;
            //var response = instance.GetDdfileByRef(xmlref, format);
            //Assert.IsInstanceOf<System.IO.Stream> (response, "response is System.IO.Stream");
        }
        
        /// <summary>
        /// Test GetDdfileBySearch
        /// </summary>
        [Test]
        public void GetDdfileBySearchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string gtin = null;
            //string fwVersion = null;
            //string hwVersion = null;
            //string format = null;
            //var response = instance.GetDdfileBySearch(gtin, fwVersion, hwVersion, format);
            //Assert.IsInstanceOf<System.IO.Stream> (response, "response is System.IO.Stream");
        }
        
        /// <summary>
        /// Test GetDdfileFromModelId
        /// </summary>
        [Test]
        public void GetDdfileFromModelIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string modelId = null;
            //string format = null;
            //var response = instance.GetDdfileFromModelId(modelId, format);
            //Assert.IsInstanceOf<System.IO.Stream> (response, "response is System.IO.Stream");
        }
        
        /// <summary>
        /// Test GetDdfileFromNaed
        /// </summary>
        [Test]
        public void GetDdfileFromNaedTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string naed = null;
            //string format = null;
            //var response = instance.GetDdfileFromNaed(naed, format);
            //Assert.IsInstanceOf<System.IO.Stream> (response, "response is System.IO.Stream");
        }
        
        /// <summary>
        /// Test GetFamiliyFile
        /// </summary>
        [Test]
        public void GetFamiliyFileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetFamiliyFile();
            //Assert.IsInstanceOf<System.IO.Stream> (response, "response is System.IO.Stream");
        }
        
    }

}
