/* 
 * DDStore API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DdInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DdInfoTests
    {
        // TODO uncomment below to declare an instance variable for DdInfo
        //private DdInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DdInfo
            //instance = new DdInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DdInfo
        /// </summary>
        [Test]
        public void DdInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DdInfo
            //Assert.IsInstanceOfType<DdInfo> (instance, "variable 'instance' is a DdInfo");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Serial'
        /// </summary>
        [Test]
        public void SerialTest()
        {
            // TODO unit test for the property 'Serial'
        }
        /// <summary>
        /// Test the property 'Gtin'
        /// </summary>
        [Test]
        public void GtinTest()
        {
            // TODO unit test for the property 'Gtin'
        }
        /// <summary>
        /// Test the property 'BasicCode'
        /// </summary>
        [Test]
        public void BasicCodeTest()
        {
            // TODO unit test for the property 'BasicCode'
        }
        /// <summary>
        /// Test the property 'Naed'
        /// </summary>
        [Test]
        public void NaedTest()
        {
            // TODO unit test for the property 'Naed'
        }
        /// <summary>
        /// Test the property 'ModelId'
        /// </summary>
        [Test]
        public void ModelIdTest()
        {
            // TODO unit test for the property 'ModelId'
        }
        /// <summary>
        /// Test the property 'DeviceTypeName'
        /// </summary>
        [Test]
        public void DeviceTypeNameTest()
        {
            // TODO unit test for the property 'DeviceTypeName'
        }
        /// <summary>
        /// Test the property 'FwVersion'
        /// </summary>
        [Test]
        public void FwVersionTest()
        {
            // TODO unit test for the property 'FwVersion'
        }
        /// <summary>
        /// Test the property 'HwVersion'
        /// </summary>
        [Test]
        public void HwVersionTest()
        {
            // TODO unit test for the property 'HwVersion'
        }
        /// <summary>
        /// Test the property 'DeviceDescription'
        /// </summary>
        [Test]
        public void DeviceDescriptionTest()
        {
            // TODO unit test for the property 'DeviceDescription'
        }
        /// <summary>
        /// Test the property 'InterfaceType'
        /// </summary>
        [Test]
        public void InterfaceTypeTest()
        {
            // TODO unit test for the property 'InterfaceType'
        }
        /// <summary>
        /// Test the property 'EcgType'
        /// </summary>
        [Test]
        public void EcgTypeTest()
        {
            // TODO unit test for the property 'EcgType'
        }
        /// <summary>
        /// Test the property 'DocUrl'
        /// </summary>
        [Test]
        public void DocUrlTest()
        {
            // TODO unit test for the property 'DocUrl'
        }
        /// <summary>
        /// Test the property 'PicRef'
        /// </summary>
        [Test]
        public void PicRefTest()
        {
            // TODO unit test for the property 'PicRef'
        }
        /// <summary>
        /// Test the property 'XmlRef'
        /// </summary>
        [Test]
        public void XmlRefTest()
        {
            // TODO unit test for the property 'XmlRef'
        }
        /// <summary>
        /// Test the property 'ScopePC'
        /// </summary>
        [Test]
        public void ScopePCTest()
        {
            // TODO unit test for the property 'ScopePC'
        }
        /// <summary>
        /// Test the property 'ScopeCloud'
        /// </summary>
        [Test]
        public void ScopeCloudTest()
        {
            // TODO unit test for the property 'ScopeCloud'
        }
        /// <summary>
        /// Test the property 'ScopeField'
        /// </summary>
        [Test]
        public void ScopeFieldTest()
        {
            // TODO unit test for the property 'ScopeField'
        }
        /// <summary>
        /// Test the property 'DriverType'
        /// </summary>
        [Test]
        public void DriverTypeTest()
        {
            // TODO unit test for the property 'DriverType'
        }

    }

}
