/* 
 * DDStore API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDdFileApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Returns a single xml file for the given xml reference from a DdInfo.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xmlref">A xml file reference.</param>
        /// <param name="format">Optional paramter to select the xml format, default is \&quot;dd\&quot; as the existing dd file or \&quot;fea\&quot; for the new format. (optional, default to dd)</param>
        /// <returns>System.IO.Stream</returns>
        System.IO.Stream GetDdfileByRef (string xmlref, string format = null);

        /// <summary>
        /// Returns a single xml file for the given xml reference from a DdInfo.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xmlref">A xml file reference.</param>
        /// <param name="format">Optional paramter to select the xml format, default is \&quot;dd\&quot; as the existing dd file or \&quot;fea\&quot; for the new format. (optional, default to dd)</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        ApiResponse<System.IO.Stream> GetDdfileByRefWithHttpInfo (string xmlref, string format = null);
        /// <summary>
        /// Returns a single xml file matching the given parameters.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gtin">Mandatory parameter to identify the xml</param>
        /// <param name="fwVersion">Optional paramter to select a xml for the given firmware version (optional)</param>
        /// <param name="hwVersion">Optional paramter to select a xml for the given hardware version (optional)</param>
        /// <param name="format">Optional paramter to select the xml format, default is \&quot;dd\&quot; as the existing dd file or \&quot;fea\&quot; for the new format. (optional, default to dd)</param>
        /// <returns>System.IO.Stream</returns>
        System.IO.Stream GetDdfileBySearch (string gtin, string fwVersion = null, string hwVersion = null, string format = null);

        /// <summary>
        /// Returns a single xml file matching the given parameters.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gtin">Mandatory parameter to identify the xml</param>
        /// <param name="fwVersion">Optional paramter to select a xml for the given firmware version (optional)</param>
        /// <param name="hwVersion">Optional paramter to select a xml for the given hardware version (optional)</param>
        /// <param name="format">Optional paramter to select the xml format, default is \&quot;dd\&quot; as the existing dd file or \&quot;fea\&quot; for the new format. (optional, default to dd)</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        ApiResponse<System.IO.Stream> GetDdfileBySearchWithHttpInfo (string gtin, string fwVersion = null, string hwVersion = null, string format = null);
        /// <summary>
        /// Returns a single xml file matching the given modelId.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelId">Mandatory parameter to identify the xml</param>
        /// <param name="format">Optional paramter to select the xml format, default is \&quot;dd\&quot; as the existing dd file or \&quot;fea\&quot; for the new format. (optional, default to dd)</param>
        /// <returns>System.IO.Stream</returns>
        System.IO.Stream GetDdfileFromModelId (string modelId, string format = null);

        /// <summary>
        /// Returns a single xml file matching the given modelId.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelId">Mandatory parameter to identify the xml</param>
        /// <param name="format">Optional paramter to select the xml format, default is \&quot;dd\&quot; as the existing dd file or \&quot;fea\&quot; for the new format. (optional, default to dd)</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        ApiResponse<System.IO.Stream> GetDdfileFromModelIdWithHttpInfo (string modelId, string format = null);
        /// <summary>
        /// Returns a single xml file matching the given naed.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="naed">Mandatory parameter to identify the xml</param>
        /// <param name="format">Optional paramter to select the xml format, default is \&quot;dd\&quot; as the existing dd file or \&quot;fea\&quot; for the new format. (optional, default to dd)</param>
        /// <returns>System.IO.Stream</returns>
        System.IO.Stream GetDdfileFromNaed (string naed, string format = null);

        /// <summary>
        /// Returns a single xml file matching the given naed.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="naed">Mandatory parameter to identify the xml</param>
        /// <param name="format">Optional paramter to select the xml format, default is \&quot;dd\&quot; as the existing dd file or \&quot;fea\&quot; for the new format. (optional, default to dd)</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        ApiResponse<System.IO.Stream> GetDdfileFromNaedWithHttpInfo (string naed, string format = null);
        /// <summary>
        /// Returns the family programming file.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>System.IO.Stream</returns>
        System.IO.Stream GetFamiliyFile ();

        /// <summary>
        /// Returns the family programming file.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        ApiResponse<System.IO.Stream> GetFamiliyFileWithHttpInfo ();
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Returns a single xml file for the given xml reference from a DdInfo.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xmlref">A xml file reference.</param>
        /// <param name="format">Optional paramter to select the xml format, default is \&quot;dd\&quot; as the existing dd file or \&quot;fea\&quot; for the new format. (optional, default to dd)</param>
        /// <returns>Task of System.IO.Stream</returns>
        System.Threading.Tasks.Task<System.IO.Stream> GetDdfileByRefAsync (string xmlref, string format = null);

        /// <summary>
        /// Returns a single xml file for the given xml reference from a DdInfo.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xmlref">A xml file reference.</param>
        /// <param name="format">Optional paramter to select the xml format, default is \&quot;dd\&quot; as the existing dd file or \&quot;fea\&quot; for the new format. (optional, default to dd)</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> GetDdfileByRefAsyncWithHttpInfo (string xmlref, string format = null);
        /// <summary>
        /// Returns a single xml file matching the given parameters.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gtin">Mandatory parameter to identify the xml</param>
        /// <param name="fwVersion">Optional paramter to select a xml for the given firmware version (optional)</param>
        /// <param name="hwVersion">Optional paramter to select a xml for the given hardware version (optional)</param>
        /// <param name="format">Optional paramter to select the xml format, default is \&quot;dd\&quot; as the existing dd file or \&quot;fea\&quot; for the new format. (optional, default to dd)</param>
        /// <returns>Task of System.IO.Stream</returns>
        System.Threading.Tasks.Task<System.IO.Stream> GetDdfileBySearchAsync (string gtin, string fwVersion = null, string hwVersion = null, string format = null);

        /// <summary>
        /// Returns a single xml file matching the given parameters.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gtin">Mandatory parameter to identify the xml</param>
        /// <param name="fwVersion">Optional paramter to select a xml for the given firmware version (optional)</param>
        /// <param name="hwVersion">Optional paramter to select a xml for the given hardware version (optional)</param>
        /// <param name="format">Optional paramter to select the xml format, default is \&quot;dd\&quot; as the existing dd file or \&quot;fea\&quot; for the new format. (optional, default to dd)</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> GetDdfileBySearchAsyncWithHttpInfo (string gtin, string fwVersion = null, string hwVersion = null, string format = null);
        /// <summary>
        /// Returns a single xml file matching the given modelId.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelId">Mandatory parameter to identify the xml</param>
        /// <param name="format">Optional paramter to select the xml format, default is \&quot;dd\&quot; as the existing dd file or \&quot;fea\&quot; for the new format. (optional, default to dd)</param>
        /// <returns>Task of System.IO.Stream</returns>
        System.Threading.Tasks.Task<System.IO.Stream> GetDdfileFromModelIdAsync (string modelId, string format = null);

        /// <summary>
        /// Returns a single xml file matching the given modelId.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelId">Mandatory parameter to identify the xml</param>
        /// <param name="format">Optional paramter to select the xml format, default is \&quot;dd\&quot; as the existing dd file or \&quot;fea\&quot; for the new format. (optional, default to dd)</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> GetDdfileFromModelIdAsyncWithHttpInfo (string modelId, string format = null);
        /// <summary>
        /// Returns a single xml file matching the given naed.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="naed">Mandatory parameter to identify the xml</param>
        /// <param name="format">Optional paramter to select the xml format, default is \&quot;dd\&quot; as the existing dd file or \&quot;fea\&quot; for the new format. (optional, default to dd)</param>
        /// <returns>Task of System.IO.Stream</returns>
        System.Threading.Tasks.Task<System.IO.Stream> GetDdfileFromNaedAsync (string naed, string format = null);

        /// <summary>
        /// Returns a single xml file matching the given naed.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="naed">Mandatory parameter to identify the xml</param>
        /// <param name="format">Optional paramter to select the xml format, default is \&quot;dd\&quot; as the existing dd file or \&quot;fea\&quot; for the new format. (optional, default to dd)</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> GetDdfileFromNaedAsyncWithHttpInfo (string naed, string format = null);
        /// <summary>
        /// Returns the family programming file.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of System.IO.Stream</returns>
        System.Threading.Tasks.Task<System.IO.Stream> GetFamiliyFileAsync ();

        /// <summary>
        /// Returns the family programming file.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> GetFamiliyFileAsyncWithHttpInfo ();
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DdFileApi : IDdFileApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DdFileApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DdFileApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DdFileApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DdFileApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Returns a single xml file for the given xml reference from a DdInfo. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xmlref">A xml file reference.</param>
        /// <param name="format">Optional paramter to select the xml format, default is \&quot;dd\&quot; as the existing dd file or \&quot;fea\&quot; for the new format. (optional, default to dd)</param>
        /// <returns>System.IO.Stream</returns>
        public System.IO.Stream GetDdfileByRef (string xmlref, string format = null)
        {
             ApiResponse<System.IO.Stream> localVarResponse = GetDdfileByRefWithHttpInfo(xmlref, format);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Returns a single xml file for the given xml reference from a DdInfo. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xmlref">A xml file reference.</param>
        /// <param name="format">Optional paramter to select the xml format, default is \&quot;dd\&quot; as the existing dd file or \&quot;fea\&quot; for the new format. (optional, default to dd)</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        public ApiResponse< System.IO.Stream > GetDdfileByRefWithHttpInfo (string xmlref, string format = null)
        {
            // verify the required parameter 'xmlref' is set
            if (xmlref == null)
                throw new ApiException(400, "Missing required parameter 'xmlref' when calling DdFileApi->GetDdfileByRef");

            var localVarPath = "/ddstore/api/v1/ddfile/{xmlref}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xmlref != null) localVarPathParams.Add("xmlref", this.Configuration.ApiClient.ParameterToString(xmlref)); // path parameter
            if (format != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "format", format)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetDdfileByRef", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<System.IO.Stream>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (System.IO.Stream) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(System.IO.Stream)));
        }

        /// <summary>
        /// Returns a single xml file for the given xml reference from a DdInfo. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xmlref">A xml file reference.</param>
        /// <param name="format">Optional paramter to select the xml format, default is \&quot;dd\&quot; as the existing dd file or \&quot;fea\&quot; for the new format. (optional, default to dd)</param>
        /// <returns>Task of System.IO.Stream</returns>
        public async System.Threading.Tasks.Task<System.IO.Stream> GetDdfileByRefAsync (string xmlref, string format = null)
        {
             ApiResponse<System.IO.Stream> localVarResponse = await GetDdfileByRefAsyncWithHttpInfo(xmlref, format);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Returns a single xml file for the given xml reference from a DdInfo. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xmlref">A xml file reference.</param>
        /// <param name="format">Optional paramter to select the xml format, default is \&quot;dd\&quot; as the existing dd file or \&quot;fea\&quot; for the new format. (optional, default to dd)</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> GetDdfileByRefAsyncWithHttpInfo (string xmlref, string format = null)
        {
            // verify the required parameter 'xmlref' is set
            if (xmlref == null)
                throw new ApiException(400, "Missing required parameter 'xmlref' when calling DdFileApi->GetDdfileByRef");

            var localVarPath = "/ddstore/api/v1/ddfile/{xmlref}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xmlref != null) localVarPathParams.Add("xmlref", this.Configuration.ApiClient.ParameterToString(xmlref)); // path parameter
            if (format != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "format", format)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetDdfileByRef", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<System.IO.Stream>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (System.IO.Stream) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(System.IO.Stream)));
        }

        /// <summary>
        /// Returns a single xml file matching the given parameters. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gtin">Mandatory parameter to identify the xml</param>
        /// <param name="fwVersion">Optional paramter to select a xml for the given firmware version (optional)</param>
        /// <param name="hwVersion">Optional paramter to select a xml for the given hardware version (optional)</param>
        /// <param name="format">Optional paramter to select the xml format, default is \&quot;dd\&quot; as the existing dd file or \&quot;fea\&quot; for the new format. (optional, default to dd)</param>
        /// <returns>System.IO.Stream</returns>
        public System.IO.Stream GetDdfileBySearch (string gtin, string fwVersion = null, string hwVersion = null, string format = null)
        {
             ApiResponse<System.IO.Stream> localVarResponse = GetDdfileBySearchWithHttpInfo(gtin, fwVersion, hwVersion, format);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Returns a single xml file matching the given parameters. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gtin">Mandatory parameter to identify the xml</param>
        /// <param name="fwVersion">Optional paramter to select a xml for the given firmware version (optional)</param>
        /// <param name="hwVersion">Optional paramter to select a xml for the given hardware version (optional)</param>
        /// <param name="format">Optional paramter to select the xml format, default is \&quot;dd\&quot; as the existing dd file or \&quot;fea\&quot; for the new format. (optional, default to dd)</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        public ApiResponse< System.IO.Stream > GetDdfileBySearchWithHttpInfo (string gtin, string fwVersion = null, string hwVersion = null, string format = null)
        {
            // verify the required parameter 'gtin' is set
            if (gtin == null)
                throw new ApiException(400, "Missing required parameter 'gtin' when calling DdFileApi->GetDdfileBySearch");

            var localVarPath = "/ddstore/api/v1/ddfile/gtin/{gtin}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (gtin != null) localVarPathParams.Add("gtin", this.Configuration.ApiClient.ParameterToString(gtin)); // path parameter
            if (fwVersion != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "fwVersion", fwVersion)); // query parameter
            if (hwVersion != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "hwVersion", hwVersion)); // query parameter
            if (format != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "format", format)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetDdfileBySearch", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<System.IO.Stream>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (System.IO.Stream) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(System.IO.Stream)));
        }

        /// <summary>
        /// Returns a single xml file matching the given parameters. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gtin">Mandatory parameter to identify the xml</param>
        /// <param name="fwVersion">Optional paramter to select a xml for the given firmware version (optional)</param>
        /// <param name="hwVersion">Optional paramter to select a xml for the given hardware version (optional)</param>
        /// <param name="format">Optional paramter to select the xml format, default is \&quot;dd\&quot; as the existing dd file or \&quot;fea\&quot; for the new format. (optional, default to dd)</param>
        /// <returns>Task of System.IO.Stream</returns>
        public async System.Threading.Tasks.Task<System.IO.Stream> GetDdfileBySearchAsync (string gtin, string fwVersion = null, string hwVersion = null, string format = null)
        {
             ApiResponse<System.IO.Stream> localVarResponse = await GetDdfileBySearchAsyncWithHttpInfo(gtin, fwVersion, hwVersion, format);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Returns a single xml file matching the given parameters. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gtin">Mandatory parameter to identify the xml</param>
        /// <param name="fwVersion">Optional paramter to select a xml for the given firmware version (optional)</param>
        /// <param name="hwVersion">Optional paramter to select a xml for the given hardware version (optional)</param>
        /// <param name="format">Optional paramter to select the xml format, default is \&quot;dd\&quot; as the existing dd file or \&quot;fea\&quot; for the new format. (optional, default to dd)</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> GetDdfileBySearchAsyncWithHttpInfo (string gtin, string fwVersion = null, string hwVersion = null, string format = null)
        {
            // verify the required parameter 'gtin' is set
            if (gtin == null)
                throw new ApiException(400, "Missing required parameter 'gtin' when calling DdFileApi->GetDdfileBySearch");

            var localVarPath = "/ddstore/api/v1/ddfile/gtin/{gtin}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (gtin != null) localVarPathParams.Add("gtin", this.Configuration.ApiClient.ParameterToString(gtin)); // path parameter
            if (fwVersion != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "fwVersion", fwVersion)); // query parameter
            if (hwVersion != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "hwVersion", hwVersion)); // query parameter
            if (format != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "format", format)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetDdfileBySearch", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<System.IO.Stream>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (System.IO.Stream) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(System.IO.Stream)));
        }

        /// <summary>
        /// Returns a single xml file matching the given modelId. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelId">Mandatory parameter to identify the xml</param>
        /// <param name="format">Optional paramter to select the xml format, default is \&quot;dd\&quot; as the existing dd file or \&quot;fea\&quot; for the new format. (optional, default to dd)</param>
        /// <returns>System.IO.Stream</returns>
        public System.IO.Stream GetDdfileFromModelId (string modelId, string format = null)
        {
             ApiResponse<System.IO.Stream> localVarResponse = GetDdfileFromModelIdWithHttpInfo(modelId, format);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Returns a single xml file matching the given modelId. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelId">Mandatory parameter to identify the xml</param>
        /// <param name="format">Optional paramter to select the xml format, default is \&quot;dd\&quot; as the existing dd file or \&quot;fea\&quot; for the new format. (optional, default to dd)</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        public ApiResponse< System.IO.Stream > GetDdfileFromModelIdWithHttpInfo (string modelId, string format = null)
        {
            // verify the required parameter 'modelId' is set
            if (modelId == null)
                throw new ApiException(400, "Missing required parameter 'modelId' when calling DdFileApi->GetDdfileFromModelId");

            var localVarPath = "/ddstore/api/v1/ddfile/modelid/{modelId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (modelId != null) localVarPathParams.Add("modelId", this.Configuration.ApiClient.ParameterToString(modelId)); // path parameter
            if (format != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "format", format)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetDdfileFromModelId", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<System.IO.Stream>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (System.IO.Stream) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(System.IO.Stream)));
        }

        /// <summary>
        /// Returns a single xml file matching the given modelId. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelId">Mandatory parameter to identify the xml</param>
        /// <param name="format">Optional paramter to select the xml format, default is \&quot;dd\&quot; as the existing dd file or \&quot;fea\&quot; for the new format. (optional, default to dd)</param>
        /// <returns>Task of System.IO.Stream</returns>
        public async System.Threading.Tasks.Task<System.IO.Stream> GetDdfileFromModelIdAsync (string modelId, string format = null)
        {
             ApiResponse<System.IO.Stream> localVarResponse = await GetDdfileFromModelIdAsyncWithHttpInfo(modelId, format);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Returns a single xml file matching the given modelId. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelId">Mandatory parameter to identify the xml</param>
        /// <param name="format">Optional paramter to select the xml format, default is \&quot;dd\&quot; as the existing dd file or \&quot;fea\&quot; for the new format. (optional, default to dd)</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> GetDdfileFromModelIdAsyncWithHttpInfo (string modelId, string format = null)
        {
            // verify the required parameter 'modelId' is set
            if (modelId == null)
                throw new ApiException(400, "Missing required parameter 'modelId' when calling DdFileApi->GetDdfileFromModelId");

            var localVarPath = "/ddstore/api/v1/ddfile/modelid/{modelId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (modelId != null) localVarPathParams.Add("modelId", this.Configuration.ApiClient.ParameterToString(modelId)); // path parameter
            if (format != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "format", format)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetDdfileFromModelId", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<System.IO.Stream>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (System.IO.Stream) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(System.IO.Stream)));
        }

        /// <summary>
        /// Returns a single xml file matching the given naed. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="naed">Mandatory parameter to identify the xml</param>
        /// <param name="format">Optional paramter to select the xml format, default is \&quot;dd\&quot; as the existing dd file or \&quot;fea\&quot; for the new format. (optional, default to dd)</param>
        /// <returns>System.IO.Stream</returns>
        public System.IO.Stream GetDdfileFromNaed (string naed, string format = null)
        {
             ApiResponse<System.IO.Stream> localVarResponse = GetDdfileFromNaedWithHttpInfo(naed, format);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Returns a single xml file matching the given naed. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="naed">Mandatory parameter to identify the xml</param>
        /// <param name="format">Optional paramter to select the xml format, default is \&quot;dd\&quot; as the existing dd file or \&quot;fea\&quot; for the new format. (optional, default to dd)</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        public ApiResponse< System.IO.Stream > GetDdfileFromNaedWithHttpInfo (string naed, string format = null)
        {
            // verify the required parameter 'naed' is set
            if (naed == null)
                throw new ApiException(400, "Missing required parameter 'naed' when calling DdFileApi->GetDdfileFromNaed");

            var localVarPath = "/ddstore/api/v1/ddfile/naed/{naed}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (naed != null) localVarPathParams.Add("naed", this.Configuration.ApiClient.ParameterToString(naed)); // path parameter
            if (format != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "format", format)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetDdfileFromNaed", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<System.IO.Stream>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (System.IO.Stream) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(System.IO.Stream)));
        }

        /// <summary>
        /// Returns a single xml file matching the given naed. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="naed">Mandatory parameter to identify the xml</param>
        /// <param name="format">Optional paramter to select the xml format, default is \&quot;dd\&quot; as the existing dd file or \&quot;fea\&quot; for the new format. (optional, default to dd)</param>
        /// <returns>Task of System.IO.Stream</returns>
        public async System.Threading.Tasks.Task<System.IO.Stream> GetDdfileFromNaedAsync (string naed, string format = null)
        {
             ApiResponse<System.IO.Stream> localVarResponse = await GetDdfileFromNaedAsyncWithHttpInfo(naed, format);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Returns a single xml file matching the given naed. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="naed">Mandatory parameter to identify the xml</param>
        /// <param name="format">Optional paramter to select the xml format, default is \&quot;dd\&quot; as the existing dd file or \&quot;fea\&quot; for the new format. (optional, default to dd)</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> GetDdfileFromNaedAsyncWithHttpInfo (string naed, string format = null)
        {
            // verify the required parameter 'naed' is set
            if (naed == null)
                throw new ApiException(400, "Missing required parameter 'naed' when calling DdFileApi->GetDdfileFromNaed");

            var localVarPath = "/ddstore/api/v1/ddfile/naed/{naed}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (naed != null) localVarPathParams.Add("naed", this.Configuration.ApiClient.ParameterToString(naed)); // path parameter
            if (format != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "format", format)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetDdfileFromNaed", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<System.IO.Stream>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (System.IO.Stream) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(System.IO.Stream)));
        }

        /// <summary>
        /// Returns the family programming file. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>System.IO.Stream</returns>
        public System.IO.Stream GetFamiliyFile ()
        {
             ApiResponse<System.IO.Stream> localVarResponse = GetFamiliyFileWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Returns the family programming file. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        public ApiResponse< System.IO.Stream > GetFamiliyFileWithHttpInfo ()
        {

            var localVarPath = "/ddstore/api/v1/ddfile/family";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetFamiliyFile", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<System.IO.Stream>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (System.IO.Stream) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(System.IO.Stream)));
        }

        /// <summary>
        /// Returns the family programming file. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of System.IO.Stream</returns>
        public async System.Threading.Tasks.Task<System.IO.Stream> GetFamiliyFileAsync ()
        {
             ApiResponse<System.IO.Stream> localVarResponse = await GetFamiliyFileAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Returns the family programming file. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> GetFamiliyFileAsyncWithHttpInfo ()
        {

            var localVarPath = "/ddstore/api/v1/ddfile/family";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetFamiliyFile", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<System.IO.Stream>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (System.IO.Stream) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(System.IO.Stream)));
        }

    }
}
